version: '2'

services:
  clickhouse-server:
    image: yandex/clickhouse-server
    hostname: clickhouse   
    restart: always
    volumes:
      - ./data/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./data/clickhouse/rabbit-servers.xml:/etc/clickhouse-server/conf.d/rabbit-servers.xml
      - ./data/clickhouse/db:/var/lib/clickhouse    
    depends_on:
      - rabbit    
    ports:
      - 8123:8123  
      - 9000:9000

  tabix-client:
    image: spoonest/clickhouse-tabix-web-client   
    hostname: tabix-client    
    restart: always
    depends_on:
      - clickhouse-server
    ports:
      - 8080:80
  
  rabbit:          
     image: rabbitmq:3.6.6-management
     hostname: rabbit
     restart: always
     volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
     environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=user
     ports:
        - "5672:5672"
        - "15672:15672"    