version: '2'

services:
  clickhouse-server:
    image: yandex/clickhouse-server
    hostname: clickhouse   
    restart: always
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/rabbit-servers.xml:/etc/clickhouse-server/conf.d/rabbit-servers.xml
      - ./clickhouse/data:/var/lib/clickhouse    
    depends_on:
      - rabbit    
    ports:
      - 8123:8123  
      - 9000:9000

  tabix-client:
    image: spoonest/clickhouse-tabix-web-client   
    hostname: tabix-client    
    restart: always
    depends_on:
      - clickhouse-server
    ports: 
      - 8080:80
  
  rabbit:          
     image: rabbitmq:3.6.6-management
     hostname: rabbit
     restart: always
     volumes:
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia    
     ports:
        - "5672:5672"
        - "15672:15672"    