version: '2'

services:
  clickhouse-server:
    image: yandex/clickhouse-server
    hostname: clickhouse
    container_name: clickhouse
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/rabbit-servers.xml:/etc/clickhouse-server/conf.d/rabbit-servers.xml
      - ./clickhouse/db:/var/lib/clickhouse    
    depends_on:
      - rabbit    
    ports:
      - 8123:8123  
      - 9000:9000

  tabix-client:
    image: spoonest/clickhouse-tabix-web-client   
    hostname: tabix-client
    container_name: tabix-client
    depends_on:
      - clickhouse-server
    ports:
      - 8080:80
  
  rabbit:
     container_name: rabbit
     hostname: rabbit
     image: rabbitmq:3.6.6-management
     environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=user
     ports:
        - "5672:5672"
        - "15672:15672"    